repos:

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black

- repo: https://github.com/pycqa/isort
  # https://stackoverflow.com/questions/75269700/pre-commit-fails-to-install-isort-5-11-4-with-error-runtimeerror-the-poetry-co/75295105#75295105
  rev: 5.11.5
  hooks:
  - id: isort

- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8

- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell
    exclude: >
        (?x)^(
            .*\.etp|
            .*\.vsw|
            .*\.scade|
            .*\.xscade|
            \.tox |
            tests/resources/.*\.xml
        )$


- repo: https://github.com/pycqa/pydocstyle
  rev: 6.3.0
  hooks:
  - id: pydocstyle
    additional_dependencies: [toml]
    exclude: "tests/"

#- repo: local
#  hooks:
#  # generate the scripts execution outputs and diagram png files
#  # in the documentation directory.
#  # raise an error when there are changes or obsolete files
#  - id: update_examples
#    name: update_examples
#    language: python
#    entry: python
#    args: [./tools/scripts/update_examples.py]
#    always_run: true
#    pass_filenames: false
#    additional_dependencies: ['ansys-scade-apitools']
