repos:

- repo: https://github.com/ansys/pre-commit-hooks
  rev: v0.2.0
  hooks:
    - id: add-license-headers
      args: ["./"]

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.1.2
  hooks:
    - id: ruff
      args: [--fix]

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell
    additional_dependencies:
      - tomli
    exclude: >
        (?x)^(
            .*\.etp|
            .*\.vsw|
            .*\.scade|
            .*\.xscade
        )$

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: check-yaml
  - id: trailing-whitespace

- repo: local
  hooks:
  # Generate the scripts execution outputs and diagram png files
  # in the documentation directory.
  # Raise an error when there are changes or obsolete files.
  - id: update_examples
    name: update_examples
    language: python
    entry: python
    args: [./tools/scripts/update_examples.py]
    always_run: true
    pass_filenames: false
    additional_dependencies: ['importlib_metadata']
