repos:

- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
  - id: black

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort

- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    additional_dependencies: [pep8-naming]

- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell
    exclude: >
        (?x)^(
            .*\.etp|
            .*\.vsw|
            .*\.scade|
            .*\.xscade|
            \.tox |
            tests/resources/.*\.xml
        )$


- repo: https://github.com/pycqa/pydocstyle
  rev: 6.3.0
  hooks:
  - id: pydocstyle
    additional_dependencies: [toml]
    exclude: "tests/"

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: check-yaml
  - id: trailing-whitespace

- repo: https://github.com/ansys/pre-commit-hooks
  rev: v0.2.0
  hooks:
    - id: add-license-headers
      args: ["./"]

- repo: local
  hooks:
  # generate the scripts execution outputs and diagram png files
  # in the documentation directory.
  # raise an error when there are changes or obsolete files
  - id: update_examples
    name: update_examples
    language: python
    entry: python
    args: [./tools/scripts/update_examples.py]
    always_run: true
    pass_filenames: false
    additional_dependencies: ['importlib_metadata']
