ci:
  autofix_commit_msg: 'chore: auto fixes from pre-commit hooks'
  autoupdate_commit_msg: 'chore: pre-commit automatic update'
  autoupdate_schedule: monthly

repos:

- repo: https://github.com/ansys/pre-commit-hooks
  rev: v0.4.4
  hooks:
  - id: add-license-headers
    args:
    - --start_year=2023

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.4
  hooks:
  - id: ruff-check
    args: [--fix]
  - id: ruff-format

- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
    args:
    - -L textIn
    additional_dependencies:
    - tomli
    exclude: >
      (?x)^(
          .*\.etp|
          .*\.vsw|
          .*\.scade|
          .*\.xscade
      )$

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: check-yaml
  - id: trailing-whitespace
    exclude: (?x)^(.*\.tot)$

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.33.2
  hooks:
  - id: check-github-workflows

- repo: https://github.com/numpy/numpydoc
  rev: v1.9.0
  hooks:
  - id: numpydoc-validation
    exclude: |
      (?x)(
          tests/
      )

- repo: https://github.com/pre-commit-ci/pre-commit-ci-config
  rev: v1.6.1
  hooks:
  - id: check-pre-commit-ci-config

# NOTE: Ruff does not check for python code in some parts of the documentation,
# e.g. python code block, ..., see https://github.com/astral-sh/ruff/issues/8237
- repo: https://github.com/adamchainz/blacken-docs
  rev: 1.19.1
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==25.1.0]
    args: [--line-length=120]

- repo: local
  hooks:
  # Generate the scripts execution outputs and diagram png files
  # in the documentation directory.
  # Raise an error when there are changes or obsolete files.
  - id: update_examples
    name: update_examples
    language: python
    entry: python
    args: [./tools/scripts/update_examples.py]
    always_run: true
    pass_filenames: false
    additional_dependencies: [importlib_metadata]
