ci:
    autofix_commit_msg: 'chore: auto fixes from pre-commit hooks'
    autoupdate_commit_msg: 'chore: pre-commit automatic update'
    autoupdate_schedule: monthly

repos:

- repo: https://github.com/ansys/pre-commit-hooks
  rev: v0.4.4
  hooks:
    - id: add-license-headers
      args:
      - --start_year=2024

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.8.0
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format

- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
    args:
    - -L textIn
    additional_dependencies:
      - tomli
    exclude: >
        (?x)^(
            .*\.etp|
            .*\.vsw|
            .*\.scade|
            .*\.xscade
        )$

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: check-yaml
  - id: trailing-whitespace
    exclude: (?x)^(.*\.tot)$

- repo: local
  hooks:
  # Generate the scripts execution outputs and diagram png files
  # in the documentation directory.
  # Raise an error when there are changes or obsolete files.
  - id: update_examples
    name: update_examples
    language: python
    entry: python
    args: [./tools/scripts/update_examples.py]
    always_run: true
    pass_filenames: false
    additional_dependencies: ['importlib_metadata']
