# action derived from pyansys/actions/tests-pytest
name: >
  Tests pytest action

description: >
  Run a test suite using `pytest <https://docs.pytest.org/en/stable/>`_.

inputs:

  scade-version:
    description: >
      SCADE version used for installing and running ``pytest``.
    required: true

  # Optional inputs
  pytest-markers:
    description: >
      Set of `pytest markers
      <https://docs.pytest.org/en/stable/example/markers.html>`_ in the form of
      a string. These markers are used to discretize tests when running the test
      session.
    default: ''
    required: false

  pytest-extra-args:
    description: >
      Set of additional ``pytest`` arguments in the form of a string.
    default: ''
    required: false

  pytest-postargs:
    description: >
      Directory of the test suite and the level of verbosity.
    default: 'tests -vv'
    required: false


runs:
  using: "composite"
  steps:
  
    - name: "Retrieve SCADE installation directory"
      uses: ansys-scade/actions/get-scade-dir@main
      id: get-scade-dir
      with:
          scade-version: ${{ inputs.scade-version }}

    - name: "Retrieve SCADE Python interpreter"
      uses: ansys-scade/actions/get-scade-python@main
      id: get-scade-python
      with:
        scade-dir: ${{ steps.get-scade-dir.outputs.scade-directory }}

    - name: "Create Python virtual environment"
      uses: ansys-scade/actions/create-scade-venv@main
      id: create-scade-venv
      with:
        python-dir: ${{ steps.get-scade-python.outputs.python-dir }}
        target-dir: '.venvs'
        target-name: ${{ steps.get-scade-python.outputs.python-name }}

    - name: "Run the tests"
      uses: ansys-scade/actions/scade-tests-pytest@main
      with:
        python-dir: ${{ steps.create-scade-venv.outputs.scripts-dir }}
        pytest-markers: ${{ inputs.pytest-markers }}
        pytest-extra-args: ${{ inputs.pytest-extra-args }}
        pytest-postargs: ${{ inputs.pytest-postargs }}
        checkout: false
